apiVersion: v1
kind: Service
metadata:
  name: my-gc-app-service
spec:
  selector:
    app: my-gc-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Assuming your app listens on port 8080
  type: NodePort
